import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Orbitron } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { UiStyleProvider } from "./UiStyleProvider";
import { ScrollXReset } from "./ScrollXReset";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const adamHeader = localFont({
  src: "./fonts/adam-header/AdamHeader.woff2",
  variable: "--font-adam-header",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const uiStyleInitScript = `
  (function () {
    try {
      var saved = window.localStorage.getItem('adam-ui-style');
      if (saved === 'classic' || saved === 'hud') {
        document.documentElement.dataset.ui = saved;
      }
    } catch (e) {
      // ignore
    }
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: uiStyleInitScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} ${orbitron.variable} ${adamHeader.variable} antialiased`}
      >
        <UiStyleProvider>
          <ScrollXReset />
          {children}
        </UiStyleProvider>
      </body>
    </html>
  );
}
